#!/bin/bash
if [ "$#" -lt 2 ];
	then echo "Usage: $0 H V [D=1]"
	xrandr | awk 'BEGIN { i = 1 } /connected/ {  printf("%d %s %s\n", i++, $1, $2); }'
	exit
fi
d=1
if [ "$#" -eq 3 ];
then
	d=$3
fi
display=$(xrandr | awk 'BEGIN { i = 0; } /connected/ { if (++i == 3) print $1;  }')

echo Display name: $display
resulotion_info="$(cvt $1 $2 | sed -n 2p | awk '{for (i=3; i<=NF;i++) print $i;}')"
resulotion_name="$(cvt $1 $2 | sed -n 2p | awk '{ print $2;}')"
echo "name=" $resulotion_name

echo xrandr --newmode $resulotion_name $resulotion_info
sudo xrandr --newmode $resulotion_name $resulotion_info

# sudo xrandr --newmode $resulotion_info
sudo xrandr --addmode $display $resulotion_name

 
