#!/bin/sh

df -h /

echo ---------------------

echo Gettiog rid of partial packages
echo Cleaning apt
apt-get clean && apt-get autoclean

echo ---------------------
echo Getting rid of no longer required packages
apt-get autoremove -y

echo ---------------------
echo Getting rid of orphaned packages
deborphan | xargs sudo apt-get -y remove --purge

# Remove the Trash
rm -rf /home/*/.local/share/Trash/*/**
rm -rf /root/.local/share/Trash/*/**

echo ---------------------
echo Cleaning the old kernels
apt-get purge $(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | head -n -1) --assume-yes
apt-get install linux-headers-`uname -r|cut -d'-' -f3`-`uname -r|cut -d'-' -f4`

echo Cleaning snap
__dir=`dirname $0`
# $__dir/clean_snap

#Cleaning is completed
echo "Cleaning is complete"


echo ---------------------
df -h
