#!/bin/bash

# Git Authors Statistics Script
# Shows percentage of code written by each author, sorted descending
# Supports single repo or directory containing multiple git repos
# Excludes autogenerated code (WCF/WSDL references, designer files, etc.)

set -e

# Colors for output
BOLD='\033[1m'
RESET='\033[0m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'

# Patterns to exclude (autogenerated code)
EXCLUDE_PATTERNS=(
    # .NET WCF/WSDL service references
    "Connected Services/"
    "Web References/"
    "Service References/"
    # Autogenerated files
    "Reference.cs"
    "*.Designer.cs"
    "*.designer.cs"
    "*.generated.cs"
    "*.g.cs"
    "*.g.i.cs"
    # Package manager directories
    "node_modules/"
    "vendor/"
    "packages/"
    # Build output
    "bin/"
    "obj/"
    "dist/"
    "build/"
)

# Temporary files for aggregation
combined_stats=$(mktemp)
trap "rm -f $combined_stats" EXIT

# Build exclusion regex from patterns
build_exclude_regex() {
    local regex=""
    for pattern in "${EXCLUDE_PATTERNS[@]}"; do
        # Convert glob pattern to regex
        local re_pattern="${pattern//\./\\.}"  # Escape dots
        re_pattern="${re_pattern//\*/.*}"      # Convert * to .*
        if [[ -n "$regex" ]]; then
            regex="$regex|$re_pattern"
        else
            regex="$re_pattern"
        fi
    done
    echo "$regex"
}

EXCLUDE_REGEX=$(build_exclude_regex)

# Function to analyze a single git repository
analyze_repo() {
    local repo_path="$1"
    local repo_name="$2"
    local tmpfile=$(mktemp)

    cd "$repo_path"

    echo -e "${GREEN}${BOLD}[$repo_name]${RESET}"
    echo -e "${BOLD}═══════════════════════════════════════════════════════════════${RESET}"

    # Show excluded files count
    local total_files=$(git ls-files | wc -l)
    local included_files=$(git ls-files | grep -Ev "$EXCLUDE_REGEX" | wc -l)
    local excluded_files=$((total_files - included_files))
    if [[ $excluded_files -gt 0 ]]; then
        echo -e "${YELLOW}Excluding $excluded_files autogenerated files${RESET}"
    fi

    # Get all tracked files and run git blame on each (excluding autogenerated)
    git ls-files | grep -Ev "$EXCLUDE_REGEX" | while read -r file; do
        # Skip binary files and files that don't exist
        if [[ -f "$file" ]] && file "$file" | grep -q "text"; then
            git blame --line-porcelain "$file" 2>/dev/null | grep "^author " | sed 's/^author //'
        fi
    done | sort | uniq -c | sort -rn > "$tmpfile"

    # Calculate total lines
    local total_lines=$(awk '{sum += $1} END {print sum}' "$tmpfile")

    if [[ -z "$total_lines" ]] || [[ "$total_lines" -eq 0 ]]; then
        echo "No code found or unable to analyze repository."
        echo ""
        rm -f "$tmpfile"
        return
    fi

    # Print header
    printf "${CYAN}%-10s  %-10s  %-s${RESET}\n" "LINES" "PERCENT" "AUTHOR"
    echo "───────────────────────────────────────────────────────────────"

    # Print statistics and append to combined stats
    while read -r count author; do
        if [[ -n "$count" ]] && [[ -n "$author" ]]; then
            percent=$(awk "BEGIN {printf \"%.2f\", ($count / $total_lines) * 100}")
            printf "%-10s  %-9s%%  %s\n" "$count" "$percent" "$author"
            # Append to combined stats file
            echo "$count $author" >> "$combined_stats"
        fi
    done < "$tmpfile"

    echo "───────────────────────────────────────────────────────────────"
    printf "${BOLD}%-10s  %-10s  %s${RESET}\n" "$total_lines" "100.00%" "TOTAL"
    echo ""

    # Cleanup
    rm -f "$tmpfile"
}

# Function to print combined statistics
print_combined_stats() {
    echo -e "${YELLOW}${BOLD}[COMBINED SUMMARY - ALL REPOSITORIES]${RESET}"
    echo -e "${BOLD}═══════════════════════════════════════════════════════════════${RESET}"

    # Aggregate by author
    local aggregated=$(mktemp)
    awk '{
        author = $2
        for (i = 3; i <= NF; i++) author = author " " $i
        counts[author] += $1
    } END {
        for (author in counts) print counts[author], author
    }' "$combined_stats" | sort -rn > "$aggregated"

    # Calculate total
    local total_lines=$(awk '{sum += $1} END {print sum}' "$aggregated")

    if [[ -z "$total_lines" ]] || [[ "$total_lines" -eq 0 ]]; then
        echo "No combined statistics available."
        rm -f "$aggregated"
        return
    fi

    printf "${CYAN}%-10s  %-10s  %-s${RESET}\n" "LINES" "PERCENT" "AUTHOR"
    echo "───────────────────────────────────────────────────────────────"

    while read -r count author; do
        if [[ -n "$count" ]] && [[ -n "$author" ]]; then
            percent=$(awk "BEGIN {printf \"%.2f\", ($count / $total_lines) * 100}")
            printf "%-10s  %-9s%%  %s\n" "$count" "$percent" "$author"
        fi
    done < "$aggregated"

    echo "───────────────────────────────────────────────────────────────"
    printf "${BOLD}%-10s  %-10s  %s${RESET}\n" "$total_lines" "100.00%" "TOTAL"
    echo ""

    rm -f "$aggregated"
}

# Main logic
main() {
    local start_dir="$(pwd)"
    local repos_found=0

    echo -e "${BOLD}Analyzing git blame statistics...${RESET}"
    echo "This may take a while for large repositories..."
    echo ""

    # Check if current directory is a git repo
    if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        # Single repo mode
        analyze_repo "$start_dir" "$(basename "$start_dir")"
        echo -e "${BOLD}Analysis complete.${RESET}"
        return
    fi

    # Multi-repo mode: find git repos in subdirectories
    for dir in */; do
        if [[ -d "$dir/.git" ]]; then
            ((++repos_found))
            analyze_repo "$start_dir/$dir" "${dir%/}"
            cd "$start_dir"
        fi
    done

    if [[ $repos_found -eq 0 ]]; then
        echo "Error: No git repositories found in current directory or subdirectories."
        exit 1
    fi

    # Print combined summary if multiple repos were analyzed
    if [[ $repos_found -gt 1 ]]; then
        print_combined_stats
    fi

    echo -e "${BOLD}Analysis complete. Analyzed $repos_found repository(ies).${RESET}"
}

main
